version: '3.9'

networks:
  flask_network:

services:
  db:
    image: postgres:14.3-alpine3.15
    build: db
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: hw_flask_db
    networks:
      flask_network:
        aliases:
            - db-main